### ISSUE TITLE
Priority incremented across listeners

### ISSUE THREAD

**Issue by marsadle** [cloudposse/terraform-aws-alb-ingress#15]
I was wondering, if there is a reason, that the priority of paths get's incremented across listeners. This makes it impossible to have default paths (priority 50000), if there is more than one listener (e.g. HTTP and HTTPS). The priority on listeners is independent of each other, so it makes no sense to base the priority on the count variable, right?

Or did I miss something?

Related code:
https://github.com/cloudposse/terraform-aws-alb-ingress/blob/0158ee7835a9b9039f90374c8660b8da4daaa3c3/main.tf#L81

https://github.com/cloudposse/terraform-aws-alb-ingress/blob/0158ee7835a9b9039f90374c8660b8da4daaa3c3/main.tf#L99

**Comment by aknysh** [comment]
@mmuehlberger 
if you provide a list of `listener_arns` to the module, you have to give each listener a different priority.
It could be done by incrementing the provided initial value (e.g. `var.unauthenticated_priority`) (as was done in the module), or by providing a list of priorities along with the list of listeners (this is more tricky).

You can provide the initial priority (e.g. `50000` in the variables (`var.unauthenticated_priority`, `var.authenticated_priority`).

Do you see/have any issues with that approach?

**Comment by marsadle** [comment]
If you have 2 listeners (one HTTP and one HTTPS) the listener rule priorities are independent from each other, therefor there is no need to increment the priority between them, as it makes setting a default rule for HTTP and HTTPS impossible (which is priority `99999` in Terraform) and has no other benefits.

When I want to set `99999` as `var.authenticated_priority` and I have 2 listeners (HTTP and HTTPS), it wants to increment the priority to `100000` for the second one, which is, of course, invalid.

_I misread my template from a couple weeks ago, where I had to use `49999` as a faux default, that's why I initially assumed `50000` is the default priority, when it is `99999` instead._

**Comment by nitrocode** [comment]
You have the option to leaving `var.authenticated_priority` or `var.unauthenticated_priority` as null and the `aws_lb_listener_rule` will be set an unused priority number for you.
