### ISSUE TITLE
Terraform 0.12 upgrade

### ISSUE THREAD

**Issue by andrewmackett** [cloudposse/terraform-aws-alb-ingress#17]
When using terraform v0.12.3 I receive the following error:
```
Error: Missing key/value separator

  on .terraform/modules/alb_ingress/main.tf line 72, in resource "aws_lb_listener_rule" "authenticated_paths_oidc":
  69: 
  70: 
  72:       authenticate_oidc {

Expected an equals sign ("=") to mark the beginning of the attribute value.
```

I assume the `action` attribute in the `aws_lb_listener_rule` resources would now be best written with a dynamic block in terraform v0.12?

**Comment by romcok** [comment]
I have the same issue. How to solve it?

**Comment by aknysh** [comment]
that was TF 0.11 syntax in TF 0.12.
the module has been converted to TF 0.12
https://github.com/cloudposse/terraform-aws-alb-ingress/releases/tag/0.9.0
