### ISSUE TITLE
Target group is currently in use by a listener or rule

### ISSUE THREAD

**Issue by archenroot** [cloudposse/terraform-aws-alb-ingress#24]
I am facing issue on recreation: 

```
Error: Error deleting Target Group: ResourceInUse: Target group 'arn:aws:elasticloadbalancing:eu-west-1::targetgroup/XXXXXX/dsfasdfasfe48' is currently in use by a listener or a rule
        status code: 400, request id: asdfasdfasdf

```

There is issue with provider at moment: https://github.com/terraform-providers/terraform-provider-aws/issues/636

I hit the issue when using from ecs_web-app module.

**Comment by ciceroneves** [comment]
Have you tried the workaround posted here?
https://github.com/terraform-providers/terraform-provider-aws/issues/1315
