### ISSUE TITLE
aws_lb_listener_rule accepts a condition of a list with a maximum size of 1

### ISSUE THREAD

**Issue by maartenvanderhoef** [cloudposse/terraform-aws-alb-ingress#9]
var.hosts can only be a list with size 1. This won't work for multiple hosts.

```
  condition {
    field  = "host-header"
    values = ["${var.hosts}"]
  }
```

**Comment by osterman** [comment]
That's true. I guess we were just passing through the expected data type which is a list. Not sure why AWS expects a list =)

**Comment by aknysh** [comment]
will close the issue for now.
AWS expects a list, but in all our code we pass a list with one item :)
